#!/usr/bin/env php
<?php

// Nạp Composer và khởi động Laravel để xử lý các lệnh Artisan.
define('LARAVEL_START', microtime(true));
require __DIR__.'/vendor/autoload.php';
$status = (require_once __DIR__.'/bootstrap/app.php')->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
exit($status);
